# site settings
title: Holly Zurenda
subtitle: Portfolio, Experience, Hobbies
email: zurend55@students.rowan.edu
description: B.S. Computer Science <br /> <br /> B.A. Mathematics (Concentration in Statistics)
baseurl: "/midtermrepo" # the subpath of your site, e.g. /blog
url: "http://holly-lyson.github.io" # the base hostname & protocol for your site
author:
street_address: 
city: Egg Harbor Township 
state: NJ
zip_code: 08234
country: United States of America
phone: (605) 377-5335

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/holly-lyson
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/hollyzurenda/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
